/**
 * Lucide Icon Map
 * Maps AccountIcon keys to Lucide React icon components
 */

import {
  Wallet,
  Car,
  ShoppingCart,
  Home,
  Pill,
  GraduationCap,
  Gamepad2,
  Plane,
  Shirt,
  Briefcase,
  UtensilsCrossed,
  Smartphone,
  Dumbbell,
  Gift,
  Package,
  Building2,
  CreditCard,
  PiggyBank,
  TrendingUp,
  ShoppingBag,
  Coffee,
  PawPrint,
  Baby,
  Church,
  Palmtree,
  Trophy,
  Music,
  BookOpen,
  Palette,
  Wrench,
  Phone,
  Laptop,
  Camera,
  Dice5,
  Tv,
  Zap,
  Droplets,
  Flame,
  Wifi,
  Shield,
  Receipt,
  Building,
  AlertTriangle,
  Banknote,
  PartyPopper,
  Utensils,
  Scissors,
  Sparkles,
  Heart,
  Stethoscope,
  Glasses,
  Bike,
  Bus,
  Train,
  Ship,
  HandHeart,
  Star,
  Diamond,
  Crown,
  Target,
  Rocket,
  Snowflake,
  Sun,
  Moon,
  Rainbow,
  Umbrella,
  KeyRound,
  Lock,
  Calendar,
  Clock,
  AlarmClock,
  Ticket,
  Calculator,
  Folder,
  Box,
  Truck,
  Factory,
  Hospital,
  School,
  Library,
  CircleDashed,
  LucideIcon,
  CircleDollarSign,
  GemIcon,
} from 'lucide-react';

import { AccountIcon } from '@/app/types/account';

// Map of AccountIcon keys to Lucide components
export const LUCIDE_ICON_MAP: Record<AccountIcon, LucideIcon> = {
  money: CircleDollarSign,
  car: Car,
  grocery: ShoppingCart,
  home: Home,
  health: Pill,
  education: GraduationCap,
  entertainment: Gamepad2,
  travel: Plane,
  clothing: Shirt,
  business: Briefcase,
  food: UtensilsCrossed,
  technology: Smartphone,
  fitness: Dumbbell,
  gifts: Gift,
  savings: Package,
  bank: Building2,
  wallet: Wallet,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  chart: TrendingUp,
  shopping: ShoppingBag,
  coffee: Coffee,
  pet: PawPrint,
  baby: Baby,
  wedding: Heart,
  vacation: Palmtree,
  sports: Trophy,
  music: Music,
  books: BookOpen,
  art: Palette,
  tools: Wrench,
  phone: Phone,
  computer: Laptop,
  camera: Camera,
  gaming: Dice5,
  streaming: Tv,
  electricity: Zap,
  water: Droplets,
  gas: Flame,
  internet: Wifi,
  insurance: Shield,
  taxes: Receipt,
  rent: Building,
  debt: AlertTriangle,
  investment: Banknote,
  emergency: AlertTriangle,
  party: PartyPopper,
  restaurant: Utensils,
  haircut: Scissors,
  spa: Sparkles,
  medicine: Stethoscope,
  dental: Stethoscope,
  glasses: Glasses,
  bicycle: Bike,
  bus: Bus,
  train: Train,
  plane: Plane,
  boat: Ship,
  charity: HandHeart,
  church: Church,
  star: Star,
  heart: Heart,
  diamond: GemIcon,
  crown: Crown,
  trophy: Trophy,
  target: Target,
  rocket: Rocket,
  fire: Flame,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  rainbow: Rainbow,
  umbrella: Umbrella,
  briefcase: Briefcase,
  graduation: GraduationCap,
  ring: Diamond,
  key: KeyRound,
  lock: Lock,
  calendar: Calendar,
  clock: Clock,
  alarm: AlarmClock,
  'gift-card': Ticket,
  coupon: Ticket,
  receipt: Receipt,
  calculator: Calculator,
  folder: Folder,
  box: Box,
  package: Package,
  truck: Truck,
  building: Building,
  factory: Factory,
  hospital: Hospital,
  school: School,
  library: Library,
  custom: CircleDashed,
};

/**
 * Get Lucide icon component for an AccountIcon key
 */
export function getLucideIcon(iconKey: AccountIcon): LucideIcon {
  return LUCIDE_ICON_MAP[iconKey] || CircleDashed;
}

/**
 * Render a Lucide icon with custom props
 */
export function renderLucideIcon(
  iconKey: AccountIcon,
  props?: { className?: string; size?: number; strokeWidth?: number }
) {
  const IconComponent = getLucideIcon(iconKey);
  return <IconComponent {...props} />;
}
